export interface CountryCode {
    name: string;
    code: string;
  }
  
  export const COUNTRY_CODES: CountryCode[] = [
    { name: 'Egypt', code: '+20' },
    { name: 'United States', code: '+1' },
    { name: 'United Kingdom', code: '+44' },
    { name: 'Saudi Arabia', code: '+966' },
    { name: 'United Arab Emirates', code: '+971' },
    { name: 'India', code: '+91' },
    { name: 'Brazil', code: '+55' },
    { name: 'China', code: '+86' },
    { name: 'France', code: '+33' },
    { name: 'Germany', code: '+49' },
    { name: 'Canada', code: '+1' },
    { name: 'Australia', code: '+61' },
    { name: 'Russia', code: '+7' },
    { name: 'Japan', code: '+81' },
    { name: 'South Korea', code: '+82' },
    { name: 'South Africa', code: '+27' },
    { name: 'Italy', code: '+39' },
    { name: 'Spain', code: '+34' },
    { name: 'Mexico', code: '+52' },
    { name: 'Indonesia', code: '+62' },
    { name: 'Turkey', code: '+90' },
    { name: 'Pakistan', code: '+92' },
    { name: 'Bangladesh', code: '+880' },
    { name: 'Nigeria', code: '+234' },
    { name: 'Argentina', code: '+54' },
    { name: 'Malaysia', code: '+60' },
    { name: 'Philippines', code: '+63' },
    { name: 'Thailand', code: '+66' },
    { name: 'Vietnam', code: '+84' },
    { name: 'Ukraine', code: '+380' },
    { name: 'Poland', code: '+48' },
    { name: 'Netherlands', code: '+31' },
    { name: 'Sweden', code: '+46' },
    { name: 'Norway', code: '+47' },
    { name: 'Denmark', code: '+45' },
    { name: 'Switzerland', code: '+41' },
    { name: 'Austria', code: '+43' },
    { name: 'Belgium', code: '+32' },
    { name: 'Greece', code: '+30' },
    { name: 'Portugal', code: '+351' },
    { name: 'Ireland', code: '+353' },
    { name: 'New Zealand', code: '+64' },
    { name: 'Singapore', code: '+65' },
    { name: 'Israel', code: '+972' },
    { name: 'Iraq', code: '+964' },
    { name: 'Morocco', code: '+212' },
    { name: 'Kenya', code: '+254' },
    { name: 'Algeria', code: '+213' },
    { name: 'Tunisia', code: '+216' },
    { name: 'Jordan', code: '+962' },
    { name: 'Qatar', code: '+974' },
    { name: 'Kuwait', code: '+965' },
    { name: 'Oman', code: '+968' },
    { name: 'Bahrain', code: '+973' },
    { name: 'Lebanon', code: '+961' },
    { name: 'Sudan', code: '+249' },
    { name: 'Ethiopia', code: '+251' },
    { name: 'Ghana', code: '+233' }
    // You can add more as needed
  ];
  